[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[services]
name = "mei-mei-bot"

[services.resources]
memory = 32768
cpu = 8
disk = 65536