[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "mei-mei-bot"

[services.resources]
memory = 32768  # 32GB RAM
cpu = 8000      # 8 vCPU
